In [1]:
# 참조
import datetime

now = datetime.datetime.now()

print(f"{now.year}년 {now.month}월{now.day}일")

2026년 7월10일

### **1. 시리즈와 데이터프레임 생성**

In [2]:
import pandas as pd

a = pd.Series(["홍길동", "김길동", "최길동", "이길동"])
print(a)
b = pd.Series(["홍길동", "김길동", "최길동", "이길동"], index=['a', 'b', 'c', 'd'])
print(b)

0    홍길동
1    김길동
2    최길동
3    이길동
dtype: str
a    홍길동
b    김길동
c    최길동
d    이길동
dtype: str

In [3]:
# 리스트로 데이터프레임 생성

list1 = list([  ["한빛", "남자", 20, 180], 
                ["한결", "남자", 21, 177], 
                ["한라", "여자", 20, 160]   ])
col_names = ["이름", "성별", "나이", "키"]

# pd.DataFrame(list1)
pd.DataFrame(list1, columns=col_names)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [4]:
# 딕셔너리로 데이터프레임 생성
dict1 = {'이름':{0:'한빛', 1:'한결', 2:'한라'},
         '성별':{0:'남자', 1:'남자', 2:'여자'},
         '나이':{0:'20', 1:'21', 2:'20'},
         '키':{0:'180', 1:'177', 2:'160'}}

pd.DataFrame(dict1)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [5]:
# 배열로 데이터프레임 생성

import numpy as np

#배열
arr1 = np.array([['한빛','남자', '20', '180'],
                 ['한결','남자', '21', '177'],
                 ['한라','여자', '20', '160']])

#열 이름 리스트
col_names = ['이름','성별','나이','키']

#데이터프레임 생성하기
pd.DataFrame(arr1, columns=col_names)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [6]:
list1 = list([['허준호','남자','30','183'],
              ['이가원','여자','24','162'],
              ['배규민','남자','23','179'],
              ['고고림','남자','21','182'],
              ['이새봄','여자','28','160'],
              ['이보람','여자','26','163'],
              ['이루리','여자','24','157'],
              ['오다현','여자','24','172']])

col_names = ['이름','성별','나이','키']

df = pd.DataFrame(list1, columns=col_names)
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [7]:
# 디렉토리에 CSV 파일로 저장하기
df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')

In [8]:
# CSV 파일 읽기
df2 = pd.read_csv('./file.csv', sep=',')
df2

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [9]:
# 열 정보
df.columns

Index(['이름', '성별', '나이', '키'], dtype='str')

In [10]:
df.describe()

         이름  성별  나이    키
count     8   8   8    8
unique    8   2   6    8
top     허준호  여자  24  183
freq      1   5   3    1

In [11]:
df.head(3)

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

In [12]:
df.tail()

    이름  성별  나이    키
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

### **2. 데이터프레임 데이터 분석**

In [13]:
# 행(index) 정렬
df.sort_index(axis=0).head()

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

In [14]:
# 열(나이, 키) 기준으로 행을 정렬
df.sort_values(by=["나이", "키"], ascending=False).head()

    이름  성별  나이    키
0  허준호  남자  30  183
4  이새봄  여자  28  160
5  이보람  여자  26  163
7  오다현  여자  24  172
1  이가원  여자  24  162

In [15]:
# 읽어오고 싶은 열만을 처리
df[["나이", "키"]].head()

   나이    키
0  30  183
1  24  162
2  23  179
3  21  182
4  28  160

In [16]:
df.iloc[1:4, 0:3]

    이름  성별  나이
1  이가원  여자  24
2  배규민  남자  23
3  고고림  남자  21

In [17]:
df[df["키"] > 180]

TypeError: '>' not supported between instances of 'str' and 'int'

In [18]:
list1 = list([['허준호','남자',30,183],
              ['이가원','여자',24,162],
              ['배규민','남자',23,179],
              ['고고림','남자',21,182],
              ['이새봄','여자',28,160],
              ['이보람','여자',26,163],
              ['이루리','여자',24,157],
              ['오다현','여자',24,172]])

col_names = ['이름','성별','나이','키']

df = pd.DataFrame(list1, columns=col_names)
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [19]:
df[df["키"] > 180]

    이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

In [20]:
df[df["나이"].isin([21, 23])]

    이름  성별  나이    키
2  배규민  남자  23  179
3  고고림  남자  21  182

In [21]:
df[(df["성별"] == "여자") & (df["키"] > 160)]

    이름  성별  나이    키
1  이가원  여자  24  162
5  이보람  여자  26  163
7  오다현  여자  24  172

In [22]:
df[(df["나이"] >= 28) | (df["성별"] == "남자")]

    이름  성별  나이    키
0  허준호  남자  30  183
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

In [23]:
# 특정 문자열("봄")을 포함하는 문자열 데이터 조회

df[df["이름"].str.contains("봄")]

    이름  성별  나이    키
4  이새봄  여자  28  160

In [24]:
# 데이터프레임 통계

df.describe()

              나이           키
count   8.000000    8.000000
mean   25.000000  169.750000
std     2.878492   10.552589
min    21.000000  157.000000
25%    23.750000  161.500000
50%    24.000000  167.500000
75%    26.500000  179.750000
max    30.000000  183.000000

In [25]:
list1 = list([['허준호','남자',30,183],
              ['이가원','여자',24,162],
              ['배규민','남자',23,179],
              ['고고림','남자',21,182],
              ['이새봄','여자',28,160],
              ['이보람','여자',26,163],
              ['이루리','여자',24,157],
              ['오다현','여자',24,172]])

col_names = ['이름','성별','나이','키']

df = pd.DataFrame(list1, columns=col_names, 
                  index=["a", "b", "c", "d", "e", "f", "g", "h"])
df

    이름  성별  나이    키
a  허준호  남자  30  183
b  이가원  여자  24  162
c  배규민  남자  23  179
d  고고림  남자  21  182
e  이새봄  여자  28  160
f  이보람  여자  26  163
g  이루리  여자  24  157
h  오다현  여자  24  172

In [26]:
# 데이터 갱신

df.loc["e", "키"] = df.loc["e", "키"] + 5
df.loc[["e"]]

    이름  성별  나이    키
e  이새봄  여자  28  165

In [27]:
# cf) iloc

# df.iloc[5, "키"] = df.iloc[5, "키"] + 5 # error
df.iloc[5, 3] = df.iloc[5, 3] + 5
df.iloc[[5]]

    이름  성별  나이    키
f  이보람  여자  26  168

In [28]:
df.loc["c":"g"]

    이름  성별  나이    키
c  배규민  남자  23  179
d  고고림  남자  21  182
e  이새봄  여자  28  165
f  이보람  여자  26  168
g  이루리  여자  24  157

In [29]:
# 반복 연산자 사용

df.loc["b":"d", "키"] = [180] * 3
df

    이름  성별  나이    키
a  허준호  남자  30  183
b  이가원  여자  24  180
c  배규민  남자  23  180
d  고고림  남자  21  180
e  이새봄  여자  28  165
f  이보람  여자  26  168
g  이루리  여자  24  157
h  오다현  여자  24  172

In [30]:
# 데이터 원복

df.loc["b":"d", "키"] = [162, 179, 182]
df

    이름  성별  나이    키
a  허준호  남자  30  183
b  이가원  여자  24  162
c  배규민  남자  23  179
d  고고림  남자  21  182
e  이새봄  여자  28  165
f  이보람  여자  26  168
g  이루리  여자  24  157
h  오다현  여자  24  172

In [31]:
# 데이터프레임 구조 수정
df.set_index("이름", inplace=True)
df

     성별  나이    키
이름
허준호  남자  30  183
이가원  여자  24  162
배규민  남자  23  179
고고림  남자  21  182
이새봄  여자  28  165
이보람  여자  26  168
이루리  여자  24  157
오다현  여자  24  172

In [32]:
# 열 추가
df["보너스"] = df["나이"] * 10000
df

     성별  나이    키     보너스
이름
허준호  남자  30  183  300000
이가원  여자  24  162  240000
배규민  남자  23  179  230000
고고림  남자  21  182  210000
이새봄  여자  28  165  280000
이보람  여자  26  168  260000
이루리  여자  24  157  240000
오다현  여자  24  172  240000

In [33]:
# 열 삭제

df.drop("보너스", axis=1, inplace=True)
df

     성별  나이    키
이름
허준호  남자  30  183
이가원  여자  24  162
배규민  남자  23  179
고고림  남자  21  182
이새봄  여자  28  165
이보람  여자  26  168
이루리  여자  24  157
오다현  여자  24  172

In [34]:
# 열 삭제

del df["보너스"]

KeyError: '보너스'

In [ ]:
# 인덱스를 기본 인덱스로 복구하고 싶다면

df.reset_index(inplace=True)
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  165
5  이보람  여자  26  168
6  이루리  여자  24  157
7  오다현  여자  24  172

In [35]:
# 데이터 치환
rep_cond = {"성별":{"남자": 1, "여자": 0}}
df2 = df.replace(rep_cond)
df2

    성별  나이    키
이름
허준호  1  30  183
이가원  0  24  162
배규민  1  23  179
고고림  1  21  182
이새봄  0  28  165
이보람  0  26  168
이루리  0  24  157
오다현  0  24  172

In [36]:
# 데이터프레임의 값 연산

# 성별 평균 키
mean_by_gender = df.groupby(by=["성별"], as_index=False)["키"].mean()
mean_by_gender.rename(columns={"키":"평균 키"}, inplace=True)
print(mean_by_gender)
print()

# 성별 키의 표준편차
std_by_gender = df.groupby(by=["성별"], as_index=False)["키"].std()
std_by_gender.rename(columns={"키":"키의 표준편차"}, inplace=True)
print(std_by_gender)

   성별        평균 키
0  남자  181.333333
1  여자  164.800000

   성별   키의 표준편차
0  남자  2.081666
1  여자  5.718391

In [37]:
# 데이터 병합
new_df = pd.merge(mean_by_gender, std_by_gender)
new_df

   성별        평균 키   키의 표준편차
0  남자  181.333333  2.081666
1  여자  164.800000  5.718391

##### **- 시계열 데이터 선택**

In [38]:
# 시계열 데이터 생성
dates = pd.date_range('2024-01-01', periods=5, freq='D')

time_series_data = pd.DataFrame({
    'date': dates,
    'sales': [100, 150, 200, 120, 180],
    'returns': [5, 8, 12, 6, 9]
})

time_series_data.set_index('date', inplace=True)

print(time_series_data)

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12
2024-01-04    120        6
2024-01-05    180        9

In [39]:
# 1) 특정 날짜 범위 선택
jan_1_to_3 = time_series_data.loc['2024-01-01':'2024-01-03']
print(jan_1_to_3)

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12

In [40]:
# 2) 연도 기준 필터링
# 2024년 데이터만 선택(연도 기준 필터링)
year_2024 = time_series_data[time_series_data.index.year == 2024]
print(year_2024)

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12
2024-01-04    120        6
2024-01-05    180        9

##### **- 파생변수 생성**

In [41]:
import pandas as pd
import numpy as np

In [42]:
# 예시 데이터 생성
sales_data = pd.DataFrame({
    'product': ['노트북', '마우스', '키보드', '모니터', '스피커'],
    'price': [1200000, 25000, 80000, 350000, 120000],
    'quantity': [10, 50, 30, 15, 25],
    'cost': [800000, 15000, 50000, 200000, 80000]
})

print(sales_data)

  product    price  quantity    cost
0     노트북  1200000        10  800000
1     마우스    25000        50   15000
2     키보드    80000        30   50000
3     모니터   350000        15  200000
4     스피커   120000        25   80000

In [43]:
# 1) 파생변수 생성

# 총 매출액 계산
sales_data['total_sales'] = sales_data['price'] * sales_data['quantity']

# 총 이익 계산
sales_data['profit'] = (sales_data['price'] - sales_data['cost']) * sales_data['quantity']

# 이익률 계산
sales_data['profit_rate'] = (sales_data['profit'] / sales_data['total_sales']) * 100

print(sales_data)

  product    price  quantity    cost  total_sales   profit  profit_rate
0     노트북  1200000        10  800000     12000000  4000000    33.333333
1     마우스    25000        50   15000      1250000   500000    40.000000
2     키보드    80000        30   50000      2400000   900000    37.500000
3     모니터   350000        15  200000      5250000  2250000    42.857143
4     스피커   120000        25   80000      3000000  1000000    33.333333

In [44]:
# 2) assgin 메서드
sales_with_rank = sales_data.assign(
    sales_rank = sales_data['total_sales'].rank(ascending=False)
)

print(sales_with_rank)

  product    price  quantity    cost  total_sales   profit  profit_rate  \
0     노트북  1200000        10  800000     12000000  4000000    33.333333
1     마우스    25000        50   15000      1250000   500000    40.000000
2     키보드    80000        30   50000      2400000   900000    37.500000
3     모니터   350000        15  200000      5250000  2250000    42.857143
4     스피커   120000        25   80000      3000000  1000000    33.333333

   sales_rank
0         1.0
1         5.0
2         4.0
3         2.0
4         3.0

##### **- apply() 함수**

In [45]:
# 제품 등급 분류 함수 정의
def classify_product_grade(row):
    if row['profit_rate'] >= 40:
        return 'A급'
    elif row['profit_rate'] >= 35:
        return 'B급'
    else:
        return 'C급'

In [46]:
# 1) DataFrame에 함수 적용

# apply를 사용하여 제품 등급 생성
sales_data['grade'] = sales_data.apply(classify_product_grade, axis=1)
print(sales_data)

  product    price  quantity    cost  total_sales   profit  profit_rate grade
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

In [47]:
# 2) 람다 함수 사용

# 람다 함수를 사용한 가격 구간 분류
sales_data['price_category'] = sales_data['price'].apply(
    lambda x: '고가' if x >= 300000 else '중가' if x >= 100000 else '저가'
)

print(sales_data)

  product    price  quantity    cost  total_sales   profit  profit_rate grade  \
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

  price_category
0             고가
1             저가
2             저가
3             고가
4             중가

In [48]:
# 3) 컬럼별 통계 계산(axis = 0)
coluns_stats = sales_data[['price', 'quantity', 'profit']].apply(np.mean)
print(f'평균값:\n{coluns_stats}')

평균값:
price        355000.0
quantity         26.0
profit      1730000.0
dtype: float64

##### **- map() & applymap() 함수**

In [ ]:
print(sales_data)

In [ ]:
# 1) map - 딕셔너리

# 카테고리 매핑 딕셔너리 생성
category_mapping = {
    '노트북': '컴퓨터',
    '마우스': '주변기기',
    '키보드': '주변기기',
    '모니터': '디스플레이',
    '스피커': '오디오'
}

grade_points = {'A급': 100, 'B급': 80, 'C급': 60}

# map을 사용한 카테고리 변환
sales_data['product_category'] = sales_data['product'].map(category_mapping)

# 등급별 포인트 매핑
sales_data['grade_points'] = sales_data['grade'].map(grade_points)
print(sales_data[['product', 'product_category', 'grade', 'grade_points']])

In [ ]:
# 2) map - 함수

# 숫자 데이터에 함수 적용 (소수점 반올림)
numeric_columns = ['profit_rate']
sales_data['profit_rate_rounded'] = sales_data['profit_rate'].map(lambda x: round(x, 1))

print(sales_data[['product', 'profit_rate', 'profit_rate_rounded']])

##### **조건부 파생변수 생성 (np.where, np.select)**

In [ ]:
# 1) np.where

# np.where를 사용한 이진 분류
sales_data['is_profitable'] = np.where(sales_data['profit'] > 1000000, '고수익', '일반수익')
print(sales_data[['product', 'profit', 'is_profitable']])

In [ ]:
# 2) np.select

# np.select를 사용한 다중 조건 분류
conditions = [
    sales_data['total_sales'] >= 10000000,
    sales_data['total_sales'] >= 5000000,
    sales_data['total_sales'] >= 2000000
]

choices = ['대형거래', '중형거래', '소형거래']

sales_data['transaction_size'] = np.select(conditions, choices, default='미니거래')
print(sales_data[['product', 'total_sales', 'is_profitable']])

In [ ]:
# 3) pd.cut

# pd.cut을 사용한 구간 분할
price_bins = [0, 50000, 200000, float('inf')]
price_labels = ['저가', '중가', '고가']
sales_data['price_segment'] = pd.cut(sales_data['price'], bins=price_bins, labels=price_labels)

print(sales_data[['product', 'price', 'price_segment']])

##### **집계 함수를 활용한 파생변수 생성**

In [ ]:
# 제품 카테고리별 평균 수익률 계산
sales_data['category_avg_profit_rate'] = sales_data.groupby('product_category')['profit_rate'].transform('mean')

# 제품 카테고리별 총 매출 대비 비중 계산
sales_data['category_total_sales'] = sales_data.groupby('product_category')['total_sales'].transform('sum')
sales_data['sales_share_in_category'] = (sales_data['total_sales'] / sales_data['category_total_sales']) * 100

print(sales_data[['product', 'product_category', 'profit_rate', 'category_avg_profit_rate', 'sales_share_in_category']])

In [ ]:
# 정렬 후 누적 합계 계산 (매출 순위별 누적 매출)
sales_sorted = sales_data.sort_values('total_sales', ascending=False)
sales_sorted['cumulative_sales'] = sales_sorted['total_sales'].cumsum()
sales_sorted['cumulative_sales_ratio'] = (sales_sorted['cumulative_sales'] / sales_sorted['total_sales'].sum()) * 100

print(sales_sorted[['product', 'total_sales', 'cumulative_sales', 'cumulative_sales_ratio']].round(1))