# **- (교재) 3.3 주가 데이터 탐색적 데이터 분석 실습**

## **-EDA(Exploratory Data Analysis)**
- 데이터를 본격적으로 모델링하기 전에 데이터의 특성을 파악하는 과정
- 즉, 데이터를 시각화하고 요약 통계를 활용하여 데이터의 특성과 패턴을 이해하고, 이후의 분석이나 머신러닝 모델링 방향을 결정하기 위한 탐색 과정을 의미
- 일반적으로 다음과 같은 작업을 포함
    - 데이터의 구조 확인 (shape, info())
    - 기술 통계 확인 (describe())
    - 결측치 및 이상치 확인
    - 변수의 분포 확인 (히스토그램, 박스플롯 등)
    - 변수 간 관계 분석 (산점도, 상관계수 등)
    - 데이터 품질 및 전처리 방향 결정

In [1]:
# yfinance 패키지 설치가 필요한 경우, 아래 코드 실행
# !pip install yfinance      # 실제 설치는 터미널에서 진행하자.

In [2]:
import yfinance as yf
import pandas as pd

df = yf.download("NVDA", period="1y", interval="1d", multi_level_index = False)
df.head()

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open     Volume
Date
2025-07-11  164.700638  167.666689  163.252570  163.502237  193633300
2025-07-14  163.851776  165.269886  161.804500  165.150035  136975800
2025-07-15  170.472946  172.170682  168.974941  170.962300  230627400
2025-07-16  171.142059  171.521559  168.675343  170.832474  158831500
2025-07-17  172.769897  173.928358  170.602786  171.791205  160841100

In [3]:
df.tail()

                 Close        High         Low        Open     Volume
Date
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.160004  195.059998  195.179993  147419100
2026-07-09  202.779999  204.589996  198.960007  204.460007  132037400
2026-07-10  210.960007  211.000000  201.919998  202.000000  148124000

In [4]:
# 1. 기본 정보 확인
print("Shape:", df.shape)
print("\n====== Info: ======")
df.info()
print("\n====== Describe: ======")
print(df.describe())

Shape: (251, 5)

====== Info: ======
<class 'pandas.DataFrame'>
DatetimeIndex: 251 entries, 2025-07-11 to 2026-07-10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   251 non-null    float64
 1   High    251 non-null    float64
 2   Low     251 non-null    float64
 3   Open    251 non-null    float64
 4   Volume  251 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 11.8 KB

====== Describe: ======
            Close        High         Low        Open        Volume
count  251.000000  251.000000  251.000000  251.000000  2.510000e+02
mean   188.218148  190.890184  185.425059  188.314537  1.739116e+08
std     13.881252   14.367515   13.489374   13.931130  4.571212e+07
min    163.851776  165.269886  161.804500  163.502237  6.552850e+07
25%    178.412056  181.164041  175.750928  178.527266  1.438414e+08
50%    184.744675  187.231201  182.127868  184.564607  1.651380e+08
75%    196.005623  199.651339  192.900002  195.585538  1.916750e+08
max    235.465576  236.264633  229.033071  229.602402  3.608079e+08

In [5]:
# 2. 컬럼명과 데이터 타입
print("컬럼명:", df.columns.tolist())
print("데이터 타입:")
print(df.dtypes)

컬럼명: ['Close', 'High', 'Low', 'Open', 'Volume']
데이터 타입:
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [6]:
# 3. 첫 5개, 마지막 5개 행
print("첫 5개 행:")
print(df.head())
print("\n마지막 5개 행:")
print(df.tail())

첫 5개 행:
                 Close        High         Low        Open     Volume
Date
2025-07-11  164.700638  167.666689  163.252570  163.502237  193633300
2025-07-14  163.851776  165.269886  161.804500  165.150035  136975800
2025-07-15  170.472946  172.170682  168.974941  170.962300  230627400
2025-07-16  171.142059  171.521559  168.675343  170.832474  158831500
2025-07-17  172.769897  173.928358  170.602786  171.791205  160841100

마지막 5개 행:
                 Close        High         Low        Open     Volume
Date
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.160004  195.059998  195.179993  147419100
2026-07-09  202.779999  204.589996  198.960007  204.460007  132037400
2026-07-10  210.960007  211.000000  201.919998  202.000000  148124000

In [7]:
# 4. 종가 기본 통계
print(f"종가 최대값: {df['Close'].max():.0f}")
print(f"종가 최소값: {df['Close'].min():.0f}")
print(f"종가 평균값: {df['Close'].mean():.0f}")

종가 최대값: 235
종가 최소값: 164
종가 평균값: 188

In [8]:
# 5. 거래량 통계
print(f"거래량 평균: {df['Volume'].mean():,.0f}")
print(f"거래량 중앙값: {df['Volume'].median():,.0f}")
print(f"거래량 표준편차: {df['Volume'].std():,.0f}")

거래량 평균: 173,911,572
거래량 중앙값: 165,138,000
거래량 표준편차: 45,712,116

In [9]:
# 6. 고가-저가 차이 평균
high_low_diff = df['High'] - df['Low']
print(f"고가-저가 차이 평균: {high_low_diff.mean(): .0f}")

고가-저가 차이 평균:  5

In [10]:
# 7. 특정 컬럼 선택
selected_df = df[['Close', 'Volume']].copy()
print(selected_df.head())

                 Close     Volume
Date
2025-07-11  164.700638  193633300
2025-07-14  163.851776  136975800
2025-07-15  170.472946  230627400
2025-07-16  171.142059  158831500
2025-07-17  172.769897  160841100

In [11]:
# 8. 최근 10개 데이터
recent_10 = df.tail(10)
print(recent_10)

                 Close        High         Low        Open     Volume
Date
2026-06-26  192.529999  195.550003  191.220001  193.119995  179304100
2026-06-29  194.970001  196.179993  189.800003  193.850006  148835700
2026-06-30  200.089996  200.630005  195.110001  197.240005  166476700
2026-07-01  197.580002  199.850006  193.449997  196.199997  146147600
2026-07-02  194.830002  200.059998  192.350006  197.139999  142068700
2026-07-06  195.550003  197.550003  193.990005  194.419998  108999000
2026-07-07  196.929993  198.410004  191.139999  192.369995  124154600
2026-07-08  204.119995  205.160004  195.059998  195.179993  147419100
2026-07-09  202.779999  204.589996  198.960007  204.460007  132037400
2026-07-10  210.960007  211.000000  201.919998  202.000000  148124000

In [12]:
# 9. 종가 상위 10% 이상 필터링
threshold = df['Close'].quantile(0.9)
high_price = df[df['Close'] >= threshold]
print(f"종가 {threshold:.7f} 이상인 날: {len(high_price)}일")

종가 209.0064087 이상인 날: 26일

In [13]:
# 10. 평균 거래량보다 많은 날
avg_volume = df['Volume'].mean()
high_volume_days = df[df['Volume'] > avg_volume]
print(f'평균 거래량({avg_volume:,.0f})보다 많았던 날: {len(high_volume_days)}일')

평균 거래량(173,911,572)보다 많았던 날: 107일

In [14]:
# 11. 거래량 내림차순 정렬
volume_sorted = df.sort_values('Volume', ascending=False)
print(volume_sorted['Volume'].head())

Date
2026-02-26    360807900
2025-11-21    346926200
2025-11-20    343504800
2025-12-19    324925900
2025-11-25    320600300
Name: Volume, dtype: int64

In [15]:
# 12. 일일 변동폭
df['Daily_Change'] = df['Close'] - df['Open']
print(df[['Open', 'Close', 'Daily_Change']].head())

                  Open       Close  Daily_Change
Date
2025-07-11  163.502237  164.700638      1.198401
2025-07-14  165.150035  163.851776     -1.298259
2025-07-15  170.962300  170.472946     -0.489354
2025-07-16  170.832474  171.142059      0.309585
2025-07-17  171.791205  172.769897      0.978692

In [16]:
# 13. 변동률
df['Change_Rate'] = ((df['Close'] - df['Open']) / df['Open'] * 100).round(2)
print(df[['Open', 'Close', 'Change_Rate']].head())

                  Open       Close  Change_Rate
Date
2025-07-11  163.502237  164.700638         0.73
2025-07-14  165.150035  163.851776        -0.79
2025-07-15  170.962300  170.472946        -0.29
2025-07-16  170.832474  171.142059         0.18
2025-07-17  171.791205  172.769897         0.57

In [17]:
# 14. 날짜 정보 추출
df['Year'] = df.index.year
df['Month'] = df.index.month
df['Weekday'] = df.index.day_name()
print(df[['Year', 'Month', 'Weekday']].head())

            Year  Month    Weekday
Date
2025-07-11  2025      7     Friday
2025-07-14  2025      7     Monday
2025-07-15  2025      7    Tuesday
2025-07-16  2025      7  Wednesday
2025-07-17  2025      7   Thursday

In [18]:
# 15. 월별 집계
monthly_stats = df.groupby('Month').agg({
    'Close': 'mean',
    'Volume': 'sum'
}).round(0)
print(monthly_stats)

       Close      Volume
Month
1      186.0  3292228600
2      185.0  3745445000
3      178.0  4027150800
4      195.0  3129548700
5      215.0  3324840700
6      207.0  3424306300
7      181.0  3388038500
8      179.0  3608891200
9      176.0  3890495300
10     188.0  4031017400
11     188.0  4160148300
12     182.0  3629693700

In [19]:
# 16. 연도별 최고가, 최저가
yearly_stats = df.groupby('Year').agg({
    'High': 'max',
    'Low': 'min'
})
print(yearly_stats)

            High         Low
Year
2025  211.919725  161.804500
2026  236.264633  164.078776

In [ ]:
# 17. 연속 상승일 계산
df['Price_Up'] = (df['Close'] > df['Open']).astype(int)
df['Consecutive_Up'] = df['Price_Up'].groupby((df['Price_Up'] != df['Price_Up'].shift()).cumsum()).cumsum()
max_consecutive = df['Consecutive_Up'].max()
print(f"최대 연속 상승일: {max_consecutive}일")

최대 연속 상승일: 8일