### **1. 시리즈와 데이터프레임 생성**
   ##### 동일한 자료형의 인덱스가 붙은 1차원 데이터 배열(엑셀의 딱 1개의 열)

In [ ]:
import pandas as pd

a = pd.Series(["홍길동", "김길동", "최길동", "이길동"])
print(a)

b = pd.Series(["홍길동", "김길동", "최길동", "이길동"], index=['a', 'b', 'c', 'd'])
print(b)

0    홍길동
1    김길동
2    최길동
3    이길동
dtype: str
a    홍길동
b    김길동
c    최길동
d    이길동
dtype: str

In [6]:
# 리스트로 데이터프레임 생성
# 2차원 리스트 데이터
list1 = list([['한빛', '남자', '20', '180'], 
              ['한결', '남자', '21', '177'], 
              ['한라', '여자', '22', '160']])

col_names = ['이름', '성별', '나이', '키']  # 속성

pd.DataFrame(list1, columns=col_names)
# pd.DataFrame(list1)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  22  160

In [ ]:
# 딕셔너리로 데이터프레임 생성, Series에 데이터를 담는 형태와 동일
dict1 = {'이름':{0:'한빛', 1:'한결', 2:'한라'},
         '성별':{0:'남자', 1:'남자', 2:'여자'},
         '나이':{0:'20', 1:'21', 2:'20'},
         '키':{0:'180', 1:'177', 2:'160'}}

pd.DataFrame(dict1)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [8]:
# 배열로 데이터프레임 생성

import numpy as np

#배열
arr1 = np.array([['한빛','남자', '20', '180'],
                 ['한결','남자', '21', '177'],
                 ['한라','여자', '20', '160']])

#열 이름 리스트
col_names = ['이름','성별','나이','키']

#데이터프레임 생성하기
pd.DataFrame(arr1, columns=col_names)

   이름  성별  나이    키
0  한빛  남자  20  180
1  한결  남자  21  177
2  한라  여자  20  160

In [ ]:
list1 = list([['허준호','남자','30','183'],
              ['이가원','여자','24','162'],
              ['배규민','남자','23','179'],
              ['고고림','남자','21','182'],
              ['이새봄','여자','28','160'],
              ['이보람','여자','26','163'],
              ['이루리','여자','24','157'],
              ['오다현','여자','24','172']])

col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names)
df

df.describe( ) # 모든 데이터를 문자열로 저장

         이름  성별  나이    키
count     8   8   8    8
unique    8   2   6    8
top     허준호  여자  24  183
freq      1   5   3    1

In [ ]:
list1 = list([['허준호','남자','30','183'],
              ['이가원','여자','24','162'],
              ['배규민','남자','23','179'],
              ['고고림','남자','21','182'],
              ['이새봄','여자','28','160'],
              ['이보람','여자','26','163'],
              ['이루리','여자','24','157'],
              ['오다현','여자','24','172']])

col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names)

# pandas는 if 조건문 없이 조건식만으로 행을 필터링 할 수 있다
df['나이'] = df['나이'].astype(int)
df['키'] = df['키'].astype(int)

over_25 = df[df['나이'] > 25]
over_180 = df[df['키'] > 180]
print(over_25)
print()
print(over_180)

# 수학 및 통계 연산 (반복문 없이 한 줄로 처리)
print(f"\n 평균나이 : {df['나이'].astype(int).mean()} 평균키 : {df['키'].astype(int).mean()}")
# print(f"\n 평균키   : {df['키'].astype(int).mean()}")

In [ ]:
# 디렉토리에 CSV 파일로 저장하기

df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')  # 실행하고 있는 파일의 현재 위치   index=True or False  index 저장여부

In [ ]:
# CSV 파일 열기

df2 = pd.read_csv('./file.csv', sep=',')
df2

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
# 열 정보

df.columns

Index(['이름', '성별', '나이', '키'], dtype='str')

In [ ]:
# 열별 값의 개수, 빈도수와 같은 통계를 확인
# count는 값의 개수, unique는 유일한 값의 개수, top은 제일 개수가 많은 값이고, freq는 빈도수(frequency)이므로 그 개수를 나타냄
df.describe( )
df.head()  # 상위 5개의 데이터만 가져옴(대략적인 특징만 보고 데이터에 대한 특징을 파악하고자 할때)
df.head(3)
# df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179

In [41]:
df.tail() # 뒤에서 부터 5개의 데이터를 가져옴
df.tail(2)

    이름  성별  나이    키
6  이루리  여자  24  157
7  오다현  여자  24  172

### **2. 데이터프레임 데이터 분석**

In [ ]:
# pandas
# 인스턴스 = Object = 객체
# DataFrame에서 feature(속성)

# 메서드 체인 : 연속적으로 함수를 호출(.을 통해서 함수를 연결)
# 행(index) 정렬
df.sort_index(axis=0).head()   # axis=0(행), axis=1(열)을 기준으로 정렬, head() 상위 5개 데이터를 가져옴(default 5), df.sort_index(axis=0).head()는 인덱스를 기준으로 정렬

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

In [ ]:

# 열(나이, 키)을 기준으로 정렬
# sort_values 컬럼의 값을 기준으로 정렬
# 동일한 데이터인 경우 다음 기준을 지정(동시에 여러개 기준을 지정)
df.sort_values(by=['나이','키'], ascending=False).head()  # 내림차순 기준으로 출력, head()를 통해 상위 5개 값을 가져옴

    이름  성별  나이    키
0  허준호  남자  30  183
4  이새봄  여자  28  160
5  이보람  여자  26  163
7  오다현  여자  24  172
1  이가원  여자  24  162

In [45]:
# 읽어오고 싶은 열만을 처리

df[['나이', '키']].head()

   나이    키
0  30  183
1  24  162
2  23  179
3  21  182
4  28  160

In [ ]:
# index location 접근방법
df
df.iloc[1:4, 0:3]   # iloc는 변수 : 1, 2, 3의 행 인덱스  0, 1, 2의 열 인덱스의 데이터

    이름  성별  나이
1  이가원  여자  24
2  배규민  남자  23
3  고고림  남자  21

In [ ]:
df[df['키'].astype(int) > 180]

Empty DataFrame
Columns: [이름, 성별, 나이, 키]
Index: []

In [73]:
list1 = list([['허준호','남자', 30 , 183 ],
              ['이가원','여자', 24 , 162 ],
              ['배규민','남자', 23 , 179 ],
              ['고고림','남자', 21 , 182 ],
              ['이새봄','여자', 28 , 160 ],
              ['이보람','여자', 26 , 163 ],
              ['이루리','여자', 24 , 157 ],
              ['오다현','여자', 24 , 172 ]])

col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names)

df[df['키'].astype(int) > 180]

    이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

In [74]:
# dataFrame이나 Series 에서 지정한 여러개의 값중 하나라도 포함되어 있는가를 검사
# isin() : 다중 조건 필터링

df[df['나이'].isin([21, 23])]

    이름  성별  나이    키
2  배규민  남자  23  179
3  고고림  남자  21  182

In [76]:
df[ (df['성별'] == '여자') & (df['키'] >= 160)]  # dataFrame에서는 논리연산자 and는 & 로 정의

    이름  성별  나이    키
1  이가원  여자  24  162
4  이새봄  여자  28  160
5  이보람  여자  26  163
7  오다현  여자  24  172

In [65]:
df[ (df['나이'] >= 28) | (df['성별'] == '남자')] # dataFrame에서 or 논리연산자는 | 로 정의

    이름  성별  나이    키
0  허준호  남자  30  183
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160

In [ ]:
# 특정 문자열을 포함하는 문자열 데이터 조회
df[df['이름'].str.contains('봄')]

    이름  성별  나이    키
4  이새봄  여자  28  160

In [ ]:
# dateFrame 통계
# 1/4 분위값, 2/4 분위값, 3/4 분위값, 4/4 분위값 등 출력

df.describe() # 데이터가 정수로 변환된 값이 저장되어 있는 경우 수치 데이터만 대상 : 나이, 키 데이터

              나이           키
count   8.000000    8.000000
mean   25.000000  171.000000
std     2.878492    9.797959
min    21.000000  157.000000
25%    23.750000  162.750000
50%    24.000000  171.000000
75%    26.500000  179.750000
max    30.000000  183.000000

In [ ]:
# 통계학의 대표값
# 평균
# 분산
# 표준편차 : 평균이 가지는 단점을 보완 제곱근에 루트

In [96]:
list1 = list([['허준호','남자', 30 , 183 ],
              ['이가원','여자', 24 , 162 ],
              ['배규민','남자', 23 , 179 ],
              ['고고림','남자', 21 , 182 ],
              ['이새봄','여자', 28 , 160 ],
              ['이보람','여자', 26 , 163 ],
              ['이루리','여자', 24 , 157 ],
              ['오다현','여자', 24 , 172 ]])

col_names = ['이름','성별','나이','키']
df = pd.DataFrame(list1, columns=col_names, index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df

    이름  성별  나이    키
a  허준호  남자  30  183
b  이가원  여자  24  162
c  배규민  남자  23  179
d  고고림  남자  21  182
e  이새봄  여자  28  160
f  이보람  여자  26  163
g  이루리  여자  24  157
h  오다현  여자  24  172

In [ ]:
# 데이터 갱신

# df.loc[4, '키'] = df.loc[4, '키'] + 5   # loc는 레이블의 이름
# df.loc[[4]]

df.loc['e', '키'] = df.loc['e', '키'] + 5   # loc는 레이블의 이름
df.loc[['e']]

    이름  성별  나이    키
e  이새봄  여자  28  165

In [113]:
# cf iloc
# df.iloc[5, '키'] = df.iloc[5, '키'] + 5
df.iloc[5, 3] = df.iloc[5, 3] + 5  # iloc (index의 위치)
# df.iloc[[5]]

# df.iloc[1:4, 0:3]

# df.iloc[0:5, 0:3] = df.iloc[0:5, 0:3] + 5  # iloc (index의 위치)
df.iloc[0:5, 0:3]

    이름  성별  나이
a  허준호  남자  30
b  이가원  여자  24
c  배규민  남자  23
d  고고림  남자  21
e  이새봄  여자  28

In [97]:
df.loc['c':'g'] # 레이블로 접근법, 인덱스의 경우는 직전 값까지 읽어옴

    이름  성별  나이    키
c  배규민  남자  23  179
d  고고림  남자  21  182
e  이새봄  여자  28  160
f  이보람  여자  26  163
g  이루리  여자  24  157

In [111]:
# 반복 연산자 사용

df.loc['b':'d', '키'] = [180] * 3
df

    이름  성별  나이    키
a  허준호  남자  30  183
b  이가원  여자  24  180
c  배규민  남자  23  180
d  고고림  남자  21  180
e  이새봄  여자  28  160
f  이보람  여자  26  183
g  이루리  여자  24  157
h  오다현  여자  24  172

In [108]:
# 데이터를 원복

df.loc['b' : 'd', '키'] = [162, 179, 182]
df

    이름  성별  나이    키
a  허준호  남자  30  183
b  이가원  여자  24  162
c  배규민  남자  23  179
d  고고림  남자  21  182
e  이새봄  여자  28  160
f  이보람  여자  26  173
g  이루리  여자  24  157
h  오다현  여자  24  172

In [ ]:
# 데이터프레임 구조 수정

df.set_index('이름', inplace=True) # 이름 행의 index 할당, 특정 컬럼을 인덱스로 사용하고자 할때
df

     성별  나이    키
이름
허준호  남자  30  183
이가원  여자  24  180
배규민  남자  23  180
고고림  남자  21  180
이새봄  여자  28  160
이보람  여자  26  188
이루리  여자  24  157
오다현  여자  24  172

In [115]:
# 열 추가

df['보너스'] = df['나이'] * 1000
df

     성별  나이    키    보너스
이름
허준호  남자  30  183  30000
이가원  여자  24  180  24000
배규민  남자  23  180  23000
고고림  남자  21  180  21000
이새봄  여자  28  160  28000
이보람  여자  26  188  26000
이루리  여자  24  157  24000
오다현  여자  24  172  24000

In [ ]:
# 열 삭제

df.drop('보너스', axis=1, inplace=True) # 열 기준으로 삭제하고 자신에게 그대로 업데이트

     성별  나이    키
이름
허준호  남자  30  183
이가원  여자  24  180
배규민  남자  23  180
고고림  남자  21  180
이새봄  여자  28  160
이보람  여자  26  188
이루리  여자  24  157
오다현  여자  24  172

In [ ]:
# 열 삭제

del df['보너스']
df

In [119]:
# dataFrame 원복 인덱스를 기본 인덱스로 복구하고 싶다면 set_index 원복

df.reset_index(inplace=True)
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  180
2  배규민  남자  23  180
3  고고림  남자  21  180
4  이새봄  여자  28  160
5  이보람  여자  26  188
6  이루리  여자  24  157
7  오다현  여자  24  172

In [ ]:
# 데이터 치환

rep_cnond = {'성별':{'남자': 1, '여자' : 0}}     # dictionary로 key, value 값을 셋팅
df2 = df.replace(rep_cnond) # 원본 데이터는 유지 inplace=True 를 하지 않았음
df2

    이름 성별  나이    키
0  허준호  1  30  183
1  이가원  0  24  180
2  배규민  1  23  180
3  고고림  1  21  180
4  이새봄  0  28  160
5  이보람  0  26  188
6  이루리  0  24  157
7  오다현  0  24  172

In [ ]:
# dataFrame의 값 선언
# 성별 평균 키

mean_by_gender = df.groupby(by=['성별'], as_index=False)['키'].mean()    # as_index=False dataFrame 형태로 출력(Series 컬럼(열)이 아닌)
mean_by_gender.rename(columns={'키' : '평균 키'}, inplace=True)  # dataFrame 업데이트(inplace=True)
print(mean_by_gender)

print()

# 성별 키의 표준편차
std_by_gender = df.groupby(by=['성별'], as_index=False)['키'].std()    # as_index=False dataFrame 형태로 출력(Series 컬럼(열)이 아닌)
std_by_gender.rename(columns={'키' : '키의 표준편차'}, inplace=True)  # dataFrame 업데이트(inplace=True)
print(std_by_gender)

   성별   평균 키
0  남자  181.0
1  여자  171.4

   성별    키의 표준편차
0  남자   1.732051
1  여자  13.107250

In [ ]:
# 데이터 병합

new_df = pd.merge(mean_by_gender, std_by_gender) # 두개의 서로 다른 데이터의 형태를 합침
new_df

   성별   평균 키    키의 표준편차
0  남자  181.0   1.732051
1  여자  171.4  13.107250

##### - **시계열 데이터 선택**
###### 연속적인 값을 가지는 데이터

In [11]:
# 시계열 데이터 생성

import pandas as pd

dates = pd.date_range('2024-01-01', periods=5, freq='D') # periods(주기) : 매개변수를 기준으로 하루 단위로 5개의 날짜 데이터를 연속적으로 생성

time_series_data = pd.DataFrame({   # DataFrame의 자료형을 변환 :dictionary 형태로 데이터를 정의
        'date' : dates, 
        'sales' : [100, 150, 200, 180, 200],  # Series 형태
        'returns' : [5, 8, 12, 6, 9]
})  # 최종적인 테이블 형태로 출력

time_series_data.set_index('date', inplace=True) # 특정 컬럼을 행의 인덱스로 사용('date'이 행의 이름으로 사용), 원본 데이터 유지, 업데이트 (inplace=True)

print(time_series_data)

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12
2024-01-04    180        6
2024-01-05    200        9

In [13]:
# 1) 특정 날짜 범위
jan_1_to_3 = time_series_data.loc['2024-01-01' : '2024-01-03']   # loc[] 레이블로 접근, 끝 index - 1이 아님

print(jan_1_to_3)

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12

In [14]:
# 2) 연도 기준 필터링
# 2024년 데이터만 선택(연도 기준 필터링)

year_2024 = time_series_data[time_series_data.index.year == 2024] # date_range로 생성한 데이터는 날짜 정보로 내부에서 생성(year, month, day..등으로 관리)
print(year_2024)

            sales  returns
date
2024-01-01    100        5
2024-01-02    150        8
2024-01-03    200       12
2024-01-04    180        6
2024-01-05    200        9

##### **파생변수 생성**
###### 주어진 데이터에서 유의미한 값을 도출할 때 추가적으로 선언해준 변수

In [26]:
import pandas as pd
import numpy as np

In [15]:
# 예시 데이터 생성
sales_data = pd.DataFrame({
        'product' : ['노트북', '마우스', '키보드', '모니터', '스피커'],
        'price' : [1200000, 25000, 80000, 350000, 120000],
        'quantity' : [10, 50, 30, 15, 25],
        'cost' : [800000, 15000, 50000, 200000, 80000]
})

print(sales_data)

  product    price  quantity    cost
0     노트북  1200000        10  800000
1     마우스    25000        50   15000
2     키보드    80000        30   50000
3     모니터   350000        15  200000
4     스피커   120000        25   80000

In [ ]:
# 1) 파생변수 생성

# 총 매출액 계산 (단가 * 수량)
sales_data['total_sales'] = sales_data['price'] * sales_data['quantity']  # 컬럼 추가, 기존 테이블에 존재하지 않으면 자동 추가

# 총 이익 계산 (현재매출 - 원가)
sales_data['profit'] = (sales_data['price'] - sales_data['cost']) * sales_data['quantity']

# 이익률 계산
sales_data['profit_rate'] = (sales_data['profit'] / sales_data['total_sales']) * 100
print(sales_data)

  product    price  quantity    cost  total_sales   profit  profit_rate
0     노트북  1200000        10  800000     12000000  4000000    33.333333
1     마우스    25000        50   15000      1250000   500000    40.000000
2     키보드    80000        30   50000      2400000   900000    37.500000
3     모니터   350000        15  200000      5250000  2250000    42.857143
4     스피커   120000        25   80000      3000000  1000000    33.333333

In [ ]:
# 2) assign 메서드
# DataFrame 2차원 객체, 새로운 열을 추가하거나 기존 열을 수정한 새로운 dataFrame을 반환
sales_with_rank = sales_data.assign(
        sales_rank = sales_data['total_sales'].rank(ascending=False)  # 내림차순으로 ranking을 전달
)  

print(sales_with_rank)
# sales_data['profit'] = (sales_data['price'] - sales_data['cost']) * sales_data['quantity']

  product    price  quantity    cost  total_sales   profit  profit_rate  \
0     노트북  1200000        10  800000     12000000  4000000    33.333333
1     마우스    25000        50   15000      1250000   500000    40.000000
2     키보드    80000        30   50000      2400000   900000    37.500000
3     모니터   350000        15  200000      5250000  2250000    42.857143
4     스피커   120000        25   80000      3000000  1000000    33.333333

   sales_rank
0         1.0
1         5.0
2         4.0
3         2.0
4         3.0

##### - **apply() 함수**

In [ ]:
# 제품 등급 분류 함수 정의

def classity_product_grage(row):
    if row['profit_rate'] >= 40:
        return 'A급'
    elif row['profit_rate'] >= 35:
        return 'B급'
    else:
        return 'C급'

# 실행 하면  함수에 대한 등록

In [21]:
# 1) DataFrame에 함수 적용

# apply()를 사용하여 제품 등급 생성
sales_data['grade'] = sales_data.apply(classity_product_grage, axis=1) # 함수가 전달되면서 axis의 값을 1(y축 기준) profit_rate의 axis=1 이므로 profit_rate를 열을 기준으로 처리
print(sales_data)

  product    price  quantity    cost  total_sales   profit  profit_rate grade
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

In [23]:
# 2) 람다 함수 사용

# 람다 함수를 사용한 가격 구간 분류
sales_data['price_category'] = sales_data['price'].apply(
        lambda x : '고가' if x >= 300000 else '중가' if x >= 100000 else '저가'  # 기능이 간단하면 rambda키워드 이용  rambda x : 기능 정의  [x 한개의 입력 매개변수 선언 : 기능 정의]
)

print(sales_data)

  product    price  quantity    cost  total_sales   profit  profit_rate grade  \
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

  price_category
0             고가
1             저가
2             저가
3             고가
4             중가

In [27]:
# 3) 컬럼별 통계 계산(axis=0)

coluns_state = sales_data[['price', 'quantity', 'profit']].apply(np.mean) # 별도의 지정이 없으면 default값 axis=0
print(f"평균값\n {coluns_state}")

평균값
 price        355000.0
quantity         26.0
profit      1730000.0
dtype: float64

##### **- map() & applymap() 함수**

In [28]:
print(sales_data)

  product    price  quantity    cost  total_sales   profit  profit_rate grade  \
0     노트북  1200000        10  800000     12000000  4000000    33.333333    C급
1     마우스    25000        50   15000      1250000   500000    40.000000    A급
2     키보드    80000        30   50000      2400000   900000    37.500000    B급
3     모니터   350000        15  200000      5250000  2250000    42.857143    A급
4     스피커   120000        25   80000      3000000  1000000    33.333333    C급

  price_category
0             고가
1             저가
2             저가
3             고가
4             중가

In [ ]:
# 1) map - 딕셔너리 : map을 통한 dictionary 데이터 전달
# 카테고리 매핑 딕셔너리 생성

category_mapping = {
        '노트북': '컴퓨터',
        '마우스': '주변기기',
        '키보드': '주변기기',
        '모니터': '디스플레이',
        '스피커': '오디오'
}

grade_points = {'A급' : 100, 'B급' : 80, 'C급' : 60}

# map을 사용한 카테고리 변환
sales_data['product_category'] = sales_data['product'].map(category_mapping) # 입력으로 dictionary, 함수등이 전달될 수 있다

# 등급별 포인트 매핑
sales_data['grade_points'] = sales_data['grade'].map(grade_points)

print(sales_data[['product', 'product_category', 'grade', 'grade_points']])

  product product_category grade  grade_points
0     노트북              컴퓨터    C급            60
1     마우스             주변기기    A급           100
2     키보드             주변기기    B급            80
3     모니터            디스플레이    A급           100
4     스피커              오디오    C급            60

In [32]:
# 2) map - 함수
# 숫자 데이터에 함수 적용 (소수점 반올림)

numeric_columns = ['profit_rate']
sales_data['profit_rate_rounded'] = sales_data['profit_rate'].map(lambda x: round(x, 1))

print(sales_data[['product', 'profit_rate', 'profit_rate_rounded']])

  product  profit_rate  profit_rate_rounded
0     노트북    33.333333                 33.3
1     마우스    40.000000                 40.0
2     키보드    37.500000                 37.5
3     모니터    42.857143                 42.9
4     스피커    33.333333                 33.3

##### **조건부 파생변수 생성 (np.where, np.select)**

In [ ]:
# 1) np.where (3개 parameter[boolen값, True, False]) : 3항 연산자
# np.where를 사용한 이진 분류

sales_data['is_profitable'] = np.where(sales_data['profit'] > 1000000, '고수익', '일반수익')
print(sales_data[['product', 'profit', 'is_profitable']])

  product   profit is_profitable
0     노트북  4000000           고수익
1     마우스   500000          일반수익
2     키보드   900000          일반수익
3     모니터  2250000           고수익
4     스피커  1000000          일반수익

In [38]:
# 2) np.select
# np select를 사용한 다중 조건 분류
conditions = [
    sales_data['total_sales'] >= 10000000,
    sales_data['total_sales'] >= 5000000,
    sales_data['total_sales'] >= 2000000
]

choices = ['대형거래', '중형거래', '소형거리']

sales_data['transaction_size'] = np.select(conditions, choices, default='미니거래')
print(sales_data[['product', 'total_sales',  'transaction_size']])

  product  total_sales transaction_size
0     노트북     12000000             대형거래
1     마우스      1250000             미니거래
2     키보드      2400000             소형거리
3     모니터      5250000             중형거래
4     스피커      3000000             소형거리

In [ ]:
# 3) pd.cut

# pd.cut을 사용한 구간 분할
price_bins = [0, 50000, 200000, float('inf')]
price_labels = ['저가', '중가', '고가']

sales_data['price_segment'] = pd.cut(sales_data['price'], bins=price_bins, labels=price_labels) # bins 구간의 기준값

print(sales_data[['product', 'price','price_segment']])

  product    price price_segment
0     노트북  1200000            고가
1     마우스    25000            저가
2     키보드    80000            중가
3     모니터   350000            고가
4     스피커   120000            중가

##### **집계 함수를 활용한 파생변수 생성**

In [ ]:
# 제품 카테고리별 평균 수익률 계산
# transform 출력의 폼을 최종적으로 만듬, 공통의 범주값에 동일한 값에 채워 feature
sales_data['category_avg_profit_rate'] = sales_data.groupby('product_category')['profit_rate'].transform('mean') # 있는 갯수만큼 결과를 채워줌
sales_data

# 제품 카테고리별 총 매출 대비 비중 계산
sales_data['category_total_sales'] = sales_data.groupby('product_category')['total_sales'].transform('sum') # 동일한 그룹의 갯수만큼 채워서 출력
sales_data['sales_share_in_category'] = (sales_data['total_sales'] / sales_data['category_total_sales']) * 100

print(sales_data[['product', 'product_category', 'profit_rate', 'category_avg_profit_rate', 'sales_share_in_category']])

  product product_category  profit_rate  category_avg_profit_rate  \
0     노트북              컴퓨터    33.333333                 33.333333
1     마우스             주변기기    40.000000                 38.750000
2     키보드             주변기기    37.500000                 38.750000
3     모니터            디스플레이    42.857143                 42.857143
4     스피커              오디오    33.333333                 33.333333

   sales_share_in_category
0               100.000000
1                34.246575
2                65.753425
3               100.000000
4               100.000000

In [51]:
# 정렬 후 누적 합계 계산 (매출 순위별 누적 매출)

sales_sorted = sales_data.sort_values('total_sales', ascending=False)
sales_sorted['cumulative_sales'] = sales_sorted['total_sales'].cumsum()
sales_sorted['cumulative_sales_ratio'] = (sales_sorted['cumulative_sales'] / sales_sorted['total_sales']) * 100
print(sales_sorted[['product', 'total_sales', 'cumulative_sales', 'cumulative_sales_ratio']].round(1))

  product  total_sales  cumulative_sales  cumulative_sales_ratio
0     노트북     12000000          12000000                   100.0
3     모니터      5250000          17250000                   328.6
4     스피커      3000000          20250000                   675.0
2     키보드      2400000          22650000                   943.8
1     마우스      1250000          23900000                  1912.0