In [1]:
import pandas as pd

metting_note_csv_path = '../audio/싼기타_비싼기타_final.csv'
df_rttm = pd.read_csv(metting_note_csv_path, sep='|')

display(df_rttm)

,start,end,speaker_id,duration,text
0,0.993,30.204,SPEAKER_01,29.211,지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론...
1,32.414,42.708,SPEAKER_00,10.294,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...
2,41.645,44.024,SPEAKER_01,2.379,"네, 됐어요. 시작하시죠.\n"
3,45.813,67.109,SPEAKER_00,21.296,좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 ...
4,67.227,82.786,SPEAKER_01,15.559,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\..."
5,84.659,102.564,SPEAKER_00,17.905,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...
6,103.492,117.532,SPEAKER_01,14.040,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...
7,119.759,138.676,SPEAKER_00,18.917,하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 ...
8,139.351,168.967,SPEAKER_01,29.616,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...
9,170.907,192.321,SPEAKER_00,21.414,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기...
10,192.322,193.689,SPEAKER_01,1.367,NaN
11,192.760,193.503,SPEAKER_00,0.743,NaN
12,193.823,216.571,SPEAKER_01,22.748,쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에...
13,218.579,238.120,SPEAKER_00,19.541,하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기...
14,238.120,238.677,SPEAKER_01,0.557,NaN
15,238.188,239.352,SPEAKER_00,1.164,결국은 본인이 선택한...\n
16,239.858,240.651,SPEAKER_01,0.793,NaN
17,240.297,241.006,SPEAKER_00,0.709,NaN
18,241.040,251.334,SPEAKER_01,10.294,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...
19,253.696,271.550,SPEAKER_00,17.854,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...
20,272.140,304.557,SPEAKER_01,32.417,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기...
21,306.970,326.022,SPEAKER_00,19.052,하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타...
22,326.360,335.472,SPEAKER_01,9.112,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...
23,337.548,355.925,SPEAKER_00,18.377,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...
24,356.245,363.974,SPEAKER_01,7.729,아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n
25,365.982,381.423,SPEAKER_00,15.441,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게..."
26,382.165,383.734,SPEAKER_01,1.569,어? 지금 도망가시는 건가요?\n
27,385.726,397.184,SPEAKER_00,11.458,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...
28,397.623,399.108,SPEAKER_01,1.485,NaN
29,401.437,406.601,SPEAKER_00,5.164,"아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n"
30,407.326,408.338,SPEAKER_01,1.012,화난 것 같은데?\n
31,410.093,417.451,SPEAKER_00,7.358,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n"
32,417.755,421.231,SPEAKER_01,3.476,계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 ...
33,423.644,429.348,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n

In [2]:
# 이름 넣기
name_dict = {
    'SPEAKER_00': 'AI',
    'SPEAKER_01': '홍길동'
}

df_rttm['name'] = df_rttm['speaker_id'].apply(lambda x: name_dict[x])
display(df_rttm)

,start,end,speaker_id,duration,text,name
0,0.993,30.204,SPEAKER_01,29.211,지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론...,홍길동
1,32.414,42.708,SPEAKER_00,10.294,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,AI
2,41.645,44.024,SPEAKER_01,2.379,"네, 됐어요. 시작하시죠.\n",홍길동
3,45.813,67.109,SPEAKER_00,21.296,좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 ...,AI
4,67.227,82.786,SPEAKER_01,15.559,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\...",홍길동
5,84.659,102.564,SPEAKER_00,17.905,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...,AI
6,103.492,117.532,SPEAKER_01,14.040,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...,홍길동
7,119.759,138.676,SPEAKER_00,18.917,하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 ...,AI
8,139.351,168.967,SPEAKER_01,29.616,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...,홍길동
9,170.907,192.321,SPEAKER_00,21.414,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기...,AI
10,192.322,193.689,SPEAKER_01,1.367,NaN,홍길동
11,192.760,193.503,SPEAKER_00,0.743,NaN,AI
12,193.823,216.571,SPEAKER_01,22.748,쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에...,홍길동
13,218.579,238.120,SPEAKER_00,19.541,하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기...,AI
14,238.120,238.677,SPEAKER_01,0.557,NaN,홍길동
15,238.188,239.352,SPEAKER_00,1.164,결국은 본인이 선택한...\n,AI
16,239.858,240.651,SPEAKER_01,0.793,NaN,홍길동
17,240.297,241.006,SPEAKER_00,0.709,NaN,AI
18,241.040,251.334,SPEAKER_01,10.294,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...,홍길동
19,253.696,271.550,SPEAKER_00,17.854,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...,AI
20,272.140,304.557,SPEAKER_01,32.417,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기...,홍길동
21,306.970,326.022,SPEAKER_00,19.052,하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타...,AI
22,326.360,335.472,SPEAKER_01,9.112,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...,홍길동
23,337.548,355.925,SPEAKER_00,18.377,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...,AI
24,356.245,363.974,SPEAKER_01,7.729,아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n,홍길동
25,365.982,381.423,SPEAKER_00,15.441,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게...",AI
26,382.165,383.734,SPEAKER_01,1.569,어? 지금 도망가시는 건가요?\n,홍길동
27,385.726,397.184,SPEAKER_00,11.458,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...,AI
28,397.623,399.108,SPEAKER_01,1.485,NaN,홍길동
29,401.437,406.601,SPEAKER_00,5.164,"아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n",AI
30,407.326,408.338,SPEAKER_01,1.012,화난 것 같은데?\n,홍길동
31,410.093,417.451,SPEAKER_00,7.358,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n",AI
32,417.755,421.231,SPEAKER_01,3.476,계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 ...,홍길동
33,423.644,429.348,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n,AI

In [3]:
meeting_note_txt = df_rttm[['start', 'end', 'name', 'text']].to_json(orient='records', force_ascii=False)   # orce_ascii=False 문자열 그대로 변환
print(meeting_note_txt)

[{"start":0.993,"end":30.204,"name":"홍길동","text":"지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론을 하면서 자연스럽게 대화하는 형식으로 하면서\n코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.\n자연스럽게.\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n어, 두 중에 어떤 역할 맡으실래요?\n"},{"start":32.414,"end":42.708,"name":"AI","text":"좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 네 맞아요. 준비 되셨나요?\n"},{"start":41.645,"end":44.024,"name":"홍길동","text":"네, 됐어요. 시작하시죠.\n"},{"start":45.813,"end":67.109,"name":"AI","text":"좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까\n비싼 기타보다는 부담�없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n"},{"start":67.227,"end":82.786,"name":"홍길동","text":"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타 사고 쌍기타 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n"},{"start":84.659,"end":102.564,"name":"AI","text":"그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 연주에 익숙해지면 그때 비교할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데\n"},{"start":103.492,"end":117.532,"name":"홍길동","text":"싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데 기타를 싼 거 산다고 달라지나요?\n"},{"start":119.759,"end":138.676,"name":"AI","text":"하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에 부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요.\n그리고 싼 기타도 요즘은\n통질이 꽤 좋아서 연습용으로\n"},{"start":139.351,"end":168.967,"name":"홍길동","text":"충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요?\n그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면\n자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.\n"},{"start":170.907,"end":192.321,"name":"AI","text":"하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기타를 기타의 흥미가 떨어지거나\n생각보다 연습시간이 적을 때\n아까울 수도 있습니다.\n이 기타의 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n"},{"start":192.322,"end":193.689,"name":"홍길동","text":null},{"start":192.76,"end":193.503,"name":"AI","text":null},{"start":193.823,"end":216.571,"name":"홍길동","text":"쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에요. 왜냐하면 그 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n"},{"start":218.579,"end":238.12,"name":"AI","text":"하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n"},{"start":238.12,"end":238.677,"name":"홍길동","text":null},{"start":238.188,"end":239.352,"name":"AI","text":"결국은 본인이 선택한...\n"},{"start":239.858,"end":240.651,"name":"홍길동","text":null},{"start":240.297,"end":241.006,"name":"AI","text":null},{"start":241.04,"end":251.334,"name":"홍길동","text":"근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n"},{"start":253.696,"end":271.55,"name":"AI","text":"맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.\n"},{"start":272.14,"end":304.557,"name":"홍길동","text":"아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기타를 치더라도 이게 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로 비싼 기타를 치던 사람이\n싼 기타를 치면은\n아 이게 이렇게 싸구려구나 라는 걸\n금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 그 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작하는 게 좋죠.\n"},{"start":306.97,"end":326.022,"name":"AI","text":"하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히\n연습하는 게 제일 중요하겠죠?\n"},{"start":326.36,"end":335.472,"name":"홍길동","text":"맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n"},{"start":337.548,"end":355.925,"name":"AI","text":"그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n"},{"start":356.245,"end":363.974,"name":"홍길동","text":"아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n"},{"start":365.982,"end":381.423,"name":"AI","text":"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게 이야기 나누는 게 더 중요한 것 같아요\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n"},{"start":382.165,"end":383.734,"name":"홍길동","text":"어? 지금 도망가시는 건가요?\n"},{"start":385.726,"end":397.184,"name":"AI","text":"아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 혹시 화나셨나요?\n"},{"start":397.623,"end":399.108,"name":"홍길동","text":null},{"start":401.437,"end":406.601,"name":"AI","text":"아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n"},{"start":407.326,"end":408.338,"name":"홍길동","text":"화난 것 같은데?\n"},{"start":410.093,"end":417.451,"name":"AI","text":"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n"},{"start":417.755,"end":421.231,"name":"홍길동","text":"계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n"},{"start":423.644,"end":429.348,"name":"AI","text":"알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n"}]

In [4]:
system_prompt = f'''
    너는 회의 내용을 요약하는 봇이야. 아래 회으록을 읽고, 주요 내용을 요약하라.
    결과는 마크다운 형식으로 작성한다.

    아래 형식에 맞추어 작성하라.

    # 회의 제목

    ## 주요 내용

    ## 참석자별 입장

    ## 결정 사항

    ================== 이하 회의록 ====================

    {meeting_note_txt}

'''

In [5]:
from openai import OpenAI
from dotenv import load_dotenv
import os
load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')
client = OpenAI(api_key=api_key)

In [6]:
# OpenAI API를 이용해 요약 결과 생성
response= client.chat.completions.create(
    model= 'gpt-5-nano',
    messages=[
    {"role": "system", "content": system_prompt},
    ]
)

# 요약 결과를 파일로 저장
summary = response.choices[0].message.content
summary = summary.strip()  # 좌우 공백 제거

print(summary)

# 회의 제목

쌍기타로 시작하는 게 좋냐, 비싼 기타로 시작하는 게 좋으냐 - 역할극 토론

## 주요 내용

- 회의 형식: 코미디 스탠드 스타일의 역할극으로, 대화를 자연스럽게 주고받으며 주제를 토론
- 주제: 초보가 전기기타를 시작할 때 쌍기타(저가/연습용 기타)로 시작하는 것이 좋은지, 아니면 비싼 기타로 시작하는 것이 좋은지에 대한 입장 차이 논의
- 쌍기타 시작의 장점: 부담이 적고 연습 부담이 낮아 실수에 대한 초기 스트레스를 줄이며 꾸준한 연습으로 기초를 다지는 데 유리. 실력이 향상되면 더 좋은 기타로 업그레이드하는 것도 가능
- 비싼 기타 시작의 장점: 소리와 연주감이 우수해 동기 부여가 크고, 포기하지 않도록 지속적인 연습 의지를 유지시켜 줄 수 있음. 다만 초기 비용 부담과 흠집/실수에 대한 압박이 커질 수 있음
- 양측의 고려점: 초기 비용과 부담, 흥미와 동기 부여의 유지, 장기적 성과와 만족도, 그리고 개인의 상황(예산, 학습 속도, 목표)에 따라 선택이 달라질 수 있음
- 공통 결론: 결국 중요한 것은 기타를 사랑하는 마음과 꾸준한 연습. 어떤 선택을 하든 본인의 상황에 맞춰 지속적으로 연습하는 것이 핵심
- 토론의 분위기: 서로의 관점을 존중하며 대화를 즐겼고, 토론의 승패보다는 주제에 대한 이해와 즐거움이 강조됨

## 참석자별 입장

- 홍길동
  - 주된 입장: 비싼 기타로 시작하는 것이 더 낫다는 점을 강조
  - 이유 요약: 초기 투자로 이중지출을 피할 수 있으며, 시작부터 높은 품질의 악기로 학습하는 편이 장기적으로 효율적일 수 있음. 또한 비싼 기타를 다루는 습관이 생기면 연습에 더 오래 몰입하게 되고, 흥미가 유지될 가능성이 큼
  - 반론 수용: 쌍기타의 품질 차이로 인한 한계도 인정하되, 가능하면 처음부터 좋은 악기로 시작하는 편이 더 낫다고 주장

- AI
  - 주된 입장: 쌍기타로 시작하는 것이 좋다는 점을 강조
  - 이유 요약: 초보자는 실수와 연습 부담이 크므로 부담 없는 악기로 시작해 기본기를 다지는 것이 현명. 흠집이나 실패에 대한 두려움을 줄이고 자신감을 키우는 것이 중요함. 나중에 실력이 쌓이면 충분히 더 좋은 악기로 업그레이드하는 것도 가능
  - 반론 수용: 상황에 따라 최적의 선택은 달라질 수 있으며, 지속적인 연습과 열정이 무엇보다 중요하다는 점을 강조

## 결정 사항

- 이번 토론에서 특정 방향의 결정은 내려지지 않음. 각자의 상황에 맞춰 최적의 선택을 하되, 중요한 것은 꾸준한 연습과 기타에 대한 열정임.
- 향후 개인의 상황에 맞춰 재평가하고 필요 시 재논의하기로 합의. 토론의 목적은 서로의 관점을 이해하고 기타에 대한 열정을 공유하는 것임.

In [7]:
with open('../audio/guitar_summary.md', 'w', encoding='utf-8') as f:
    f.write(summary)

In [8]:
df_meeting_note = df_rttm[['start', 'end', 'name', 'text']].copy()
df_meeting_note.dropna(inplace=True) # 항목에 데이터가 담겨저 있지 않으면 제거

meeting_note_dict = df_meeting_note.to_dict(orient='records') # 딕셔너리 형태로 변환

meeting_note_dict

[{'start': 0.993,
  'end': 30.204,
  'name': '홍길동',
  'text': '지금부터 저랑 역할극을 합시다.\n역할극을 스탠드인 코미디 스타일로 할 건데\n토론을 하면서 자연스럽게 대화하는 형식으로 하면서\n코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.\n자연스럽게.\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n어, 두 중에 어떤 역할 맡으실래요?\n'},
 {'start': 32.414,
  'end': 42.708,
  'name': 'AI',
  'text': '좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 네 맞아요. 준비 되셨나요?\n'},
 {'start': 41.645, 'end': 44.024, 'name': '홍길동', 'text': '네, 됐어요. 시작하시죠.\n'},
 {'start': 45.813,
  'end': 67.10900000000001,
  'name': 'AI',
  'text': '좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.\n초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까\n비싼 기타보다는 부담�없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n'},
 {'start': 67.227,
  'end': 82.786,
  'name': '홍길동',
  'text': '아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타 사고 쌍기타 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n'},
 {'start': 84.659,
  'end': 102.564,
  'name': 'AI',
  'text': '그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 연주에 익숙해지면 그때 비교할 수 있는 게 더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데\n'},
 {'start': 103.492,
  'end': 117.532,
  'name': '홍길동',
  'text': '싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데 기타를 싼 거 산다고 달라지나요?\n'},
 {'start': 119.759,
  'end': 138.67600000000002,
  'name': 'AI',
  'text': '하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에 부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요.\n그리고 싼 기타도 요즘은\n통질이 꽤 좋아서 연습용으로\n'},
 {'start': 139.351,
  'end': 168.96699999999998,
  'name': '홍길동',
  'text': '충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요?\n그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면\n자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.\n'},
 {'start': 170.907,
  'end': 192.321,
  'name': 'AI',
  'text': '하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기타를 기타의 흥미가 떨어지거나\n생각보다 연습시간이 적을 때\n아까울 수도 있습니다.\n이 기타의 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n'},
 {'start': 193.823,
  'end': 216.571,
  'name': '홍길동',
  'text': '쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에요. 왜냐하면 그 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n'},
 {'start': 218.579,
  'end': 238.12,
  'name': 'AI',
  'text': '하하 비싼 기타가\n일종의 동기부여가 된다는\n말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n'},
 {'start': 238.188, 'end': 239.352, 'name': 'AI', 'text': '결국은 본인이 선택한...\n'},
 {'start': 241.04,
  'end': 251.334,
  'name': '홍길동',
  'text': '근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n'},
 {'start': 253.696,
  'end': 271.55,
  'name': 'AI',
  'text': '맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.\n'},
 {'start': 272.14,
  'end': 304.557,
  'name': '홍길동',
  'text': '아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와\n비싼 기타를 치더라도 이게 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로 비싼 기타를 치던 사람이\n싼 기타를 치면은\n아 이게 이렇게 싸구려구나 라는 걸\n금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 그 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작하는 게 좋죠.\n'},
 {'start': 306.97,
  'end': 326.02200000000005,
  'name': 'AI',
  'text': '하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히\n연습하는 게 제일 중요하겠죠?\n'},
 {'start': 326.36,
  'end': 335.472,
  'name': '홍길동',
  'text': '맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n'},
 {'start': 337.548,
  'end': 355.925,
  'name': 'AI',
  'text': '그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n'},
 {'start': 356.245,
  'end': 363.974,
  'name': '홍길동',
  'text': '아 맞아요.\n그 지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n'},
 {'start': 365.982,
  'end': 381.423,
  'name': 'AI',
  'text': '아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게 이야기 나누는 게 더 중요한 것 같아요\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n'},
 {'start': 382.165,
  'end': 383.734,
  'name': '홍길동',
  'text': '어? 지금 도망가시는 건가요?\n'},
 {'start': 385.726,
  'end': 397.184,
  'name': 'AI',
  'text': '아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 혹시 화나셨나요?\n'},
 {'start': 401.437,
  'end': 406.601,
  'name': 'AI',
  'text': '아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n'},
 {'start': 407.326, 'end': 408.338, 'name': '홍길동', 'text': '화난 것 같은데?\n'},
 {'start': 410.093,
  'end': 417.451,
  'name': 'AI',
  'text': '네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n'},
 {'start': 417.755,
  'end': 421.231,
  'name': '홍길동',
  'text': '계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.\n'},
 {'start': 423.644,
  'end': 429.348,
  'name': 'AI',
  'text': '알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n'}]

In [15]:
import re
from openai import OpenAI

# OpenAI 클라이언트 초기화 (필요시 api_key 전달)
client = OpenAI()

# 1. 공통 context 및 system prompt 사전 준비
system_prompt = """너는 주어진 회의 녹취록을 수정 및 보완하는 전문가이다.
            제시된 '회의 요약문'과 '전체 녹취록'의 문맥을 참조하여, '확인할 메시지 원본'의 STT 오탈자나 문맥상 오류를 수정하라.

            [수정 규칙]
            1. 표현과 말투는 최대한 원본과 일치하도록 유지하라.
            2. 잘못 받아적은 내용, 오탈자, 불명확한 단어만 문맥에 맞게 수정하라.
            3. 설명, 이유, 서론/본론 구분 문구, '수정된 내용:' 같은 접두사 없이 **오직 수정된 메시지 텍스트만** 반환하라.
            """

# 전체 녹취록 JSON 문자열은 루프 밖에서 1회만 변환하여 재사용
meeting_note_json = df_meeting_note.to_json(orient='records', force_ascii=False)

# 2. 메시지별 보정 루프
for row in meeting_note_dict:
    # 텍스트가 아니거나 빈 값인 경우 건너뛰기
    if not isinstance(row.get('text'), str) or not row['text'].strip():
        continue

    user_prompt = f"""--------------------------------
    [회의 요약문]
    {summary}

    --------------------------------
    [회의 녹취록 전문]
    {meeting_note_json}

    --------------------------------
    [확인할 메시지 원본]
    {row['text']}"""

    response = client.chat.completions.create(
        model='gpt-5-nano',  # 사용 중이신 모델명 지정 (예: gpt-4o-mini, gpt-4o 등)
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        # temperature=0.2  # 일관되고 정확한 수정을 위해 낮은 온도 설정
    )

    correction = response.choices[0].message.content.strip()

    # 안전한 접두사 제거 (콜론이 본문에 포함되어도 문제 없도록 정규식 활용)
    correction = re.sub(r'^(수정|보완|결과|응답)\s*:\s*', '', correction)
    correction = correction.strip()

    # 결과 확인 및 저장
    print(f"화자: {row.get('name', 'Unknown')}")
    print(f"원본: {row['text']}")
    print(f"수정: {correction}")
    print('-' * 40)

    row['corrected_text'] = correction

화자: 홍길동
원본: 지금부터 저랑 역할극을 합시다.
역할극을 스탠드인 코미디 스타일로 할 건데
토론을 하면서 자연스럽게 대화하는 형식으로 하면서
코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.
자연스럽게.
그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
어, 두 중에 어떤 역할 맡으실래요?

수정: 지금부터 저랑 역할극을 합시다.
역할극을 스탠드업 코미디 스타일로 할 건데
토론을 하면서 자연스럽게 대화하는 형식으로 하면서
코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요.
자연스럽게.
그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
어, 두 중에 어떤 역할 맡으실래요?
----------------------------------------
화자: AI
원본: 좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 네 맞아요. 준비 되셨나요?

수정: 좋습니다. 그럼 제가 쌍기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠? 네, 맞아요. 준비되셨나요?
----------------------------------------
화자: 홍길동
원본: 네, 됐어요. 시작하시죠.

수정: 네, 됐어요. 시작하시죠.
----------------------------------------
화자: AI
원본: 좋아요. 먼저 3기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.
초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까
비싼 기타보다는 부담�없이 연습할 수 있는 싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?
성형님은 어떻게 생각하세요?

수정: 좋아요. 먼저 쌍기타로 시작하는 게 좋은 이유를 말씀드리겠습니다.
초보자일 때는 실수도 많고 기타에 익숙해지는 과정이 필요하니까
비싼 기타보다는 부담없이 연습할 수 있는 싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드하는 것도 나쁘지 않죠?
형님은 어떻게 생각하세요?
----------------------------------------
화자: 홍길동
원본: 아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타로
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타 사고 쌍기타 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.

수정: 아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타로
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타를 사고 쌍기타를 사게 되는데 그런 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.
----------------------------------------
화자: AI
원본: 그런데 비싼 기타로 시작하면
혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?
초보 때는 실습을 많이 하니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요.
그리고 기타 연주에 익숙해지면 그때 비교할 수 있는 게 더 좋다고 생각해요.
그리고 기타 현지에 익숙해지면
그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데

수정: 그런데 비싼 기타로 시작하면
혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?
초보 때는 연습을 많이 하니까 쌍기타로 마음 편히 연습할 수 있는 게 더 좋다고 생각해요.
그리고 기타 연주에 익숙해지면 그때 비교할 수 있는 게 더 좋다고 생각해요.
그리고 기타에 익숙해지면
그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데
----------------------------------------
화자: 홍길동
원본: 싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데 기타를 싼 거 산다고 달라지나요?

수정: 싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데, 싼 기타를 산다고 달라지나요?
----------------------------------------
화자: AI
원본: 하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에 부담없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요.
그리고 싼 기타도 요즘은
통질이 꽤 좋아서 연습용으로

수정: 하하! 기타를 망치로 치진 않지만 그래도 초보자들은 실수도 많고 조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에 부담없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요.
그리고 싼 기타도 요즘은
품질이 꽤 좋아서 연습용으로
----------------------------------------
화자: 홍길동
원본: 충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이
많이 좋아서
연습하는데 충분한 거는
맞는데
근데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요?
그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면
자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.
근데 기타가 좋은 기타다.
그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.

수정: 충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이 많이 좋아서 연습하는 데 충분한 것은 맞는데 그런데 뭐 돈이 있으면은 그냥 비싼 기타로 사서 하면 되는 거 아니에요? 그리고 기타를 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠. 근데 기타가 좋은 기타다. 그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요.
----------------------------------------
화자: AI
원본: 하하
역시 좋은 기타를 사면 책임감도
더 커진다는 말씀이시군요. 그래도 비싼 기타를 기타의 흥미가 떨어지거나
생각보다 연습시간이 적을 때
아까울 수도 있습니다.
이 기타의 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.

수정: 하하
역시 좋은 기타를 사면 책임감도
더 커진다는 말씀이시군요. 그래도 비싼 기타를 사면 흥미가 떨어지거나
생각보다 연습시간이 적을 때
아까울 수도 있습니다.
이 기타의 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.
----------------------------------------
화자: 홍길동
원본: 쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비슷하게 아니에요. 왜냐하면 그 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?
라는 생각이 들면서 계속
연습을 열심히 할 수가 있어요.
그래서 포기를 안 하게 되는
측면에서도 비싼 기타가 훨씬 도움이 된다고
생각을 합니다.

수정: 쌍기타로 시작해서 부담없이 연습하고 정말 기타에 흥미가 생기면 그때 비싼 기타로 가는 게 낫지 않나요? 왜냐하면 그 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 잃게 되죠. 그리고 비싼 기타를 사면 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나? 라는 생각이 들면서 계속 연습을 열심히 할 수가 있어요. 그래서 포기를 안 하게 되는 측면에서도 비싼 기타가 훨씬 도움이 된다고 생각을 합니다.
----------------------------------------
화자: AI
원본: 하하 비싼 기타가
일종의 동기부여가 된다는
말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.
그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.

수정: 하하 비싼 기타가
일종의 동기부여가 된다는
말씀이시군요. 하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.
그리고 좋은 기타로 나중에 업그레이드할 때 그 성취감도 크니까요.
----------------------------------------
화자: AI
원본: 결국은 본인이 선택한...

수정: 결국은 본인이 선택한 기타로 꾸준히 연습하는 것이 중요하죠.
----------------------------------------
화자: 홍길동
원본: 근데 그게 비싼 기타를 치면 더 편해요.
편하게 치는 게 중요하다고 하셨잖아요.
근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.

수정: 근데 그게 비싼 기타를 치면 더 편해요.
편하게 치는 게 중요하다고 하셨잖아요.
근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.
----------------------------------------
화자: AI
원본: 맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.
하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.
그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.
결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.

수정: 맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.
하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.
그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.
결국 각자의 스타일과 상황에 맞게 선택하는 게 최선이겠네요.
----------------------------------------
화자: 홍길동
원본: 아 그 말에 대해 동의를 합니다.
기타를 잘 못 치는 사람은
쌍기타와
비싼 기타를 치더라도 이게 비싼 기타를 치더라도 이게 왜 좋은 기타인지
이걸 잘 못 느끼긴 하죠.
근데 반대로 비싼 기타를 치던 사람이
싼 기타를 치면은
아 이게 이렇게 싸구려구나 라는 걸
금방 느낄 수가 있습니다
그래서 처음부터 비싼 기타를 쳐서
그런 그 쌍기타의 맛을 모르고 살아도 되는데
왜 그 맛없는 맛을
굳이 초반부터 느끼려고 합니까?
그러니까 비싼 기타로 시작하는 게 좋죠.

수정: 아 그 말에 동의합니다.
기타를 잘 못 치는 사람은
쌍기타와
비싼 기타를 쳐도 이게 왜 좋은 기타인지
이걸 잘 못 느끼긴 하죠.
근데 반대로 비싼 기타를 치던 사람이
싼 기타를 치면은
아 이게 이렇게 싸구려구나 라는 걸
금방 느낄 수가 있습니다
그래서 처음부터 비싼 기타를 쳐서
그런 쌍기타의 맛을 모르고 살아도 되는데
왜 그 맛없는 맛을
굳이 초반부터 느끼려고 합니까?
그러니까 비싼 기타로 시작하는 게 좋죠.
----------------------------------------
화자: AI
원본: 하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.
하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니
처음엔 가볍게 접근하는 게 더 좋다고 봅니다.
어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히
연습하는 게 제일 중요하겠죠?

수정: 하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.
하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니
처음엔 가볍게 접근하는 게 더 좋다고 봅니다.
어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히
연습하는 게 제일 중요하겠죠?
----------------------------------------
화자: 홍길동
원본: 맞아요. 그래서 비싼 기타를 사야 되는 거예요.
비싼 기타를 사면 꾸준히 연습을 하게 됩니다.
왜냐하면 계속 그 기타를 만지고 있고 싶거든요.
왜냐면 감촉도 훨씬 좋고 그러니까요.

수정: 맞아요. 그래서 비싼 기타를 사야 되는 거예요.
비싼 기타를 사면 꾸준히 연습을 하게 됩니다.
왜냐하면 계속 그 기타를 만지고 있고 싶거든요.
왜냐하면 감촉도 훨씬 좋고 그러니까요.
----------------------------------------
화자: AI
원본: 그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.
하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.
결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.
소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.

수정: 그렇죠. 비싼 기타는 확실히 소리도 좋고 연주할 때 기분도 좋으니까요.
하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.
결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.
소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.
----------------------------------------
화자: 홍길동
원본: 아 맞아요.
그 지금 얘기하신 거 보니까
쌍기타가 더 좋다는 얘기는 안 하시네요.

수정: 아 맞아요.
지금 얘기하신 거 보니까 쌍기타가 더 좋다는 얘기는 안 하시네요.
----------------------------------------
화자: AI
원본: 아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는
재밌게 이야기 나누는 게 더 중요한 것 같아요
가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.
결국 중요한 건 기타를 사랑하는 마음이겠죠.
앞으로도 즐겁게 연습하시길 바래요.

수정: 아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 이야기 나누는 게 더 중요한 것 같아요. 가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다. 결국 중요한 건 기타를 사랑하는 마음이겠죠. 앞으로도 즐겁게 연습하시길 바래요.
----------------------------------------
화자: 홍길동
원본: 어? 지금 도망가시는 건가요?

수정: 어? 지금 도망가시는 건가요?
----------------------------------------
화자: AI
원본: 아니요. 전혀 그렇지 않아요.
전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.
토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.
혹시 더 이야기하고 싶으신 게 있나요? 혹시 화나셨나요?

수정: 아니요. 전혀 화나지 않았어요.
전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.
토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.
혹시 더 이야기하고 싶으신 게 있나요? 혹시 화나셨나요?
----------------------------------------
화자: AI
원본: 아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.

수정: 아니요, 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하지 마세요.
----------------------------------------
화자: 홍길동
원본: 화난 것 같은데?

수정: 화가 난 것 같은데?
----------------------------------------
화자: AI
원본: 네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.

수정: 네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.
----------------------------------------
화자: 홍길동
원본: 계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.

수정: 계속해서 이야기를 나누고 싶으시면 편하게 말씀해주세요. 아니요. 화나셨는데 굳이 더 할 필요 없죠. 그만 잊지 마시죠.
----------------------------------------
화자: AI
원본: 알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.

수정: 알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.
----------------------------------------

In [11]:
# STT 원본을 GPT로 교정하기
# meeting_note_dict를 JSON 파일 형식으로 저장

import json

with open('../audio/guitar_meeting_note_corrected.json', 'w', encoding='utf-8') as f:
    json.dump(meeting_note_dict, f, ensure_ascii=False, indent=4)

In [12]:
# guitar_meeting_note_corrected.json 파일을 마크다운 형식으로 저장

md_template = ''

for row in meeting_note_dict:
    md_template += f"- **{row['name']}** : {row['corrected_text']}\n"

with open('../audio/guitar_meeting_note_corrected.md', 'w', encoding='utf-8') as f:
    f.write(md_template)

In [ ]:
# pip install python-docx

In [16]:
from docx import Document

document = Document()                       # (1) docx 객체 생성
document.add_heading('회의록', level=1)     # (2) 제목 추가
table = document.add_table(rows=1, cols=2)  # (3) 테이블

table.style = 'Table Grid'      # (4) 테이블 스타일 지정
hdr_cells = table.rows[0].cells # (5) 첫 번째 행에 셀 추가
hdr_cells[0].text = 'Speaker'   # (6) 첫 번째 셀에 Speaker 추가
hdr_cells[1].text = 'Content'   # (7) 두 번째 셀에 Content 추가

# (8) 수정된 녹취록 파일을 읽어들여서 테이블에 추가
for row in meeting_note_dict:
    row_cells = table.add_row().cells
    row_cells[0].text = row['name']
    row_cells[1].text = row['corrected_text']

document.save('../audio/guitar_meeting_note_corrected.docx')    # (9) docx 파일 저장